-- =============================================================================
-- UltrON — DataQuality Code Migration Reference
-- =============================================================================
-- CPCB-standard codes are UNCHANGED — no migration required.
--
-- Old:  good="U"  bad="U"  uncertain="U"  out_of_range="O"
--       comms_fail="E"  sensor_fail="E"  maintenance="U"  negative="N"
--
-- New:  good="U"  bad="B"  uncertain="I"  out_of_range="O"
--       comms_fail="E"  sensor_fail="F"  maintenance="M"  negative="N"
--       ^ CPCB    ^ new    ^ new           ^ CPCB
--                 ^ new    ^ new           ^ new     ^ CPCB
--
-- WHY NO MIGRATION IS NEEDED:
-- The old code stored ALL non-CPCB values as "U" (good, bad, uncertain,
-- maintenance were all "U").  Since "U" still means "good" (CPCB), legacy
-- records with "U" are correctly interpreted as good data.
--
-- The new distinct codes (B, I, F, M) are only used by NEW code paths
-- that never existed before — there are no legacy rows with these values.
--
-- RUN ONLY IF you deployed the intermediate "G=Good" version:
--   UPDATE historical_data SET quality = 'U' WHERE quality = 'G';
--   UPDATE live_data        SET quality = 'U' WHERE quality = 'G';
--   UPDATE averages         SET quality = 'U' WHERE quality = 'G';
-- =============================================================================
