services:
  mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: rajapi_mqtt
    ports:
      - "1883:1883"
      - "9001:9001" # WebSockets for the web dashboard
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
